# Generated by Django 5.1.7 on 2025-03-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategory_project_project_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory'),
        ),
    ]
