# Generated by Django 5.1.7 on 2025-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('heading', models.CharField(default='Data Scientist & Programmer', max_length=100)),
                ('shortbio', models.TextField(max_length=153)),
                ('skills', models.JSONField(default=list)),
                ('available_for_freelance', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
