# Generated by Django 5.1.7 on 2025-04-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_description_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
