# Generated by Django 5.1.7 on 2025-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_skill_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
