# Generated by Django 5.1.7 on 2025-04-12 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_skill_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
